# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_auto_20170328_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
    ]
