# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_auto_20170328_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerinteger',
            name='limit_lower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answerinteger',
            name='limit_upper',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
