# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_auto_20170328_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='if the question type is "radio," "select," or "select multiple" provide a comma-separated list of options for this question .', null=True),
        ),
    ]
